name: Publish to GitHub Pages

on:
  push:
    branches:
    - main
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          auto-activate-base: false
      - name: Dependencies
        shell: bash -l {0}
        run: |
          conda install pip
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
      - name: Sphinx build
        run: |
          sphinx-build source _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' && job.status == 'success'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          enable_jekyll: false
